# x-logging: &logging
#   driver: "k8s-file"
#   # driver: "json-file"
#   options:
#     max-size: "10m"
#     max-file: "3"

# Хорошая статья по настройке postgres compose: https://habr.com/ru/articles/578744/
# Код  в github: https://github.com/mfvanek/useful-sql-scripts/tree/master/running_pg_in_docker

services:
  postgres:
    container_name: postgres
    image: docker.io/postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=5GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
      # volumes:
    #   - type: tmpfs
    #     target: /var/lib/postgresql/data
    #     tmpfs:
    #       size: 100000000
    # logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      # test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres  

  # pgadmin:
  #   # pgAdmin стартует на порту 5050
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4:7.2
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "iamuser@myemail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "pgadmin"
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 1G
  #   networks:
  #     - postgres

volumes:
  postgres-data:
  # pgadmin-data:  

networks:
  postgres:
    driver: bridge

  
